
# 서버포트 번호
server:
  port: 8080

# 콘솔 ANSI 색상
spring:
  output:
    ansi:
      enabled: always

  # thymeleaf 설정
  thymeleaf:
    cache: false
    prefix: classpath:templates/views/

  # datasource 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/projectSpring?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: user907
    password: 1234

  # security
  security:
    user:
      name: user1     # 디폴트 security username
      password: 1234   #  password

    # oauth2 client
    oauth2:
      client:
        registration:
          google:
            client-id: 985769897427-e0deev7q83d7vo64torccan8nio9s27c.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          naver:
            client-id: MlkJv10B7BFiOJM3w5bo
            client-secret: S27AHr1WuU
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response





# MyBatis 매퍼(mapper) 파일 위치 설정
# src/main/resources 이하의 경로 지정
mybatis:
  mapper-locations: classpath:mapper/**/*.xml

app:
  # OAuth2
  oauth2:
    password: 1234
    # Kakao 로그인 관련 세팅값
    kakao:
      client-id: 0152884ca90470c683536696fcad8bfd   # 앱 키
      redirect-uri: http://localhost:8080/oauth2/kakao/callback  # Redirect URI
      token-uri: https://kauth.kakao.com/oauth/token   # access token 요청 URI
      user-info-uri: https://kapi.kakao.com/v2/user/me   # 사용자 profile 요청 URI

openai:
  model: gpt-3.5-turbo
  api-url: https://api.openai.com/v1/chat/completions
  api-key: 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
